<?php
// Auto-generated from ZONE BREAKDOWN LIST.xlsx
// Zone, District, Assembly mapping for Tamil Nadu (38 districts, 234 assemblies)
return [
    'district_zone' => [
        'THIRUVALLUR' => 'KANCHI ZONE',
        'KANCHEEPURAM' => 'KANCHI ZONE',
        'CHENGALPATTU' => 'KANCHI ZONE',
        'CHENNAI' => 'CHENNAI ZONE',
        'VELLORE' => 'VELLORE ZONE',
        'KRISHNAGIRI' => 'VELLORE ZONE',
        'TIRUPATHUR' => 'VELLORE ZONE',
        'RANIPET' => 'VELLORE ZONE',
        'DHARMAPURI' => 'TIRUVANNAMALAI ZONE',
        'TIRUVANNAMALAI' => 'TIRUVANNAMALAI ZONE',
        'KALLAKURUCHI' => 'TIRUVANNAMALAI ZONE',
        'VILUPURAM' => 'VILLUPURAM ZONE',
        'CUDDALORE' => 'VILLUPURAM ZONE',
        'SALEM' => 'SALEM ZONE',
        'NAMAKKAL' => 'SALEM ZONE',
        'ERODE' => 'SALEM ZONE',
        'NILGIRIS' => 'COVAI ZONE',
        'COIMBATORE' => 'COVAI ZONE',
        'TIRUPPUR' => 'COVAI ZONE',
        'KARUR' => 'TRICHY ZONE',
        'TIRUCHIRAPALLI' => 'TRICHY ZONE',
        'PERAMBALUR' => 'TRICHY ZONE',
        'PUDUKOTTAI' => 'TRICHY ZONE',
        'ARIYALUR' => 'TRICHY ZONE',
        'DINDIGUL' => 'VIRUDHUNAGAR ZONE',
        'THENI' => 'VIRUDHUNAGAR ZONE',
        'VIRUDHUNAGAR' => 'VIRUDHUNAGAR ZONE',
        'NAGAPATTINAM' => 'THANJAI ZONE',
        'THIRUVARUR' => 'THANJAI ZONE',
        'THANJAVUR' => 'THANJAI ZONE',
        'MAYILADUTHURAI' => 'THANJAI ZONE',
        'SIVAGANGA' => 'MADURAI ZONE',
        'MADURAI' => 'MADURAI ZONE',
        'RAMANATHAPURAM' => 'MADURAI ZONE',
        'THOOTHUKUDI' => 'TIRUNELVELI ZONE',
        'TIRUNELVELI' => 'TIRUNELVELI ZONE',
        'KANNIYAKUMARI' => 'TIRUNELVELI ZONE',
        'TENKASI' => 'TIRUNELVELI ZONE',
    ],
    'assembly_map' => [
        'GUMMIDIPOONDI' => ['c' => 'Gummidipoondi', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'PONNERI' => ['c' => 'Ponneri', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'TIRUTTANI' => ['c' => 'Tiruttani', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'THIRUVALLUR' => ['c' => 'Thiruvallur', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'POONAMALLEE' => ['c' => 'Poonamallee', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'AVADI' => ['c' => 'Avadi', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'MADURAVOYAL' => ['c' => 'Maduravoyal', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'AMBATTUR' => ['c' => 'Ambattur', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'MADAVARAM' => ['c' => 'Madavaram', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'THIRUVOTTIYUR' => ['c' => 'Thiruvottiyur', 'd' => 'THIRUVALLUR', 'z' => 'KANCHI ZONE'],
        'ALANDUR' => ['c' => 'Alandur', 'd' => 'KANCHEEPURAM', 'z' => 'KANCHI ZONE'],
        'SRIPERUMBUDUR' => ['c' => 'Sriperumbudur', 'd' => 'KANCHEEPURAM', 'z' => 'KANCHI ZONE'],
        'UTHIRAMERUR' => ['c' => 'Uthiramerur', 'd' => 'KANCHEEPURAM', 'z' => 'KANCHI ZONE'],
        'KANCHEEPURAM' => ['c' => 'Kancheepuram', 'd' => 'KANCHEEPURAM', 'z' => 'KANCHI ZONE'],
        'SHOZHINGANALLUR' => ['c' => 'Shozhinganallur', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'PALLAVARAM' => ['c' => 'Pallavaram', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'TAMBARAM' => ['c' => 'Tambaram', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'CHENGALPATTU' => ['c' => 'Chengalpattu', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'THIRUPORUR' => ['c' => 'Thiruporur', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'CHEYYUR' => ['c' => 'Cheyyur', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'MADURANTAKAM' => ['c' => 'Madurantakam', 'd' => 'CHENGALPATTU', 'z' => 'KANCHI ZONE'],
        'DR.RADHAKRISHNAN NAGAR' => ['c' => 'Dr.Radhakrishnan  Nagar', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'PERAMBUR' => ['c' => 'Perambur', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'KOLATHUR' => ['c' => 'Kolathur', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'VILLIVAKKAM' => ['c' => 'Villivakkam', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'THIRU-VI-KA-NAGAR' => ['c' => 'Thiru-Vi-Ka-Nagar', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'EGMORE' => ['c' => 'Egmore', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'ROYAPURAM' => ['c' => 'Royapuram', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'HARBOUR' => ['c' => 'Harbour', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'CHEPAUK-THIRUVALLIKENI' => ['c' => 'Chepauk-Thiruvallikeni', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'THOUSAND LIGHTS' => ['c' => 'Thousand Lights', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'ANNA NAGAR' => ['c' => 'Anna Nagar', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'VIRUGAMPAKKAM' => ['c' => 'Virugampakkam', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'SAIDAPET' => ['c' => 'Saidapet', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'THIYAGARAYANAGAR' => ['c' => 'Thiyagarayanagar', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'MYLAPORE' => ['c' => 'Mylapore', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'VELACHERY' => ['c' => 'Velachery', 'd' => 'CHENNAI', 'z' => 'CHENNAI ZONE'],
        'KATPADI' => ['c' => 'Katpadi', 'd' => 'VELLORE', 'z' => 'VELLORE ZONE'],
        'VELLORE' => ['c' => 'Vellore', 'd' => 'VELLORE', 'z' => 'VELLORE ZONE'],
        'ANAIKATTU' => ['c' => 'Anaikattu', 'd' => 'VELLORE', 'z' => 'VELLORE ZONE'],
        'KILVAITHINANKUPPAM' => ['c' => 'Kilvaithinankuppam', 'd' => 'VELLORE', 'z' => 'VELLORE ZONE'],
        'GUDIYATTAM' => ['c' => 'Gudiyattam', 'd' => 'VELLORE', 'z' => 'VELLORE ZONE'],
        'UTHANGARAI' => ['c' => 'Uthangarai', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'BARGUR' => ['c' => 'Bargur', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'KRISHNAGIRI' => ['c' => 'Krishnagiri', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'VEPPANAHALLI' => ['c' => 'Veppanahalli', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'HOSUR' => ['c' => 'Hosur', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'THALLI' => ['c' => 'Thalli', 'd' => 'KRISHNAGIRI', 'z' => 'VELLORE ZONE'],
        'VANIYAMBADI' => ['c' => 'Vaniyambadi', 'd' => 'TIRUPATHUR', 'z' => 'VELLORE ZONE'],
        'AMBUR' => ['c' => 'Ambur', 'd' => 'TIRUPATHUR', 'z' => 'VELLORE ZONE'],
        'JOLARPET' => ['c' => 'Jolarpet', 'd' => 'TIRUPATHUR', 'z' => 'VELLORE ZONE'],
        'TIRUPATTUR' => ['c' => 'Tirupattur', 'd' => 'TIRUPATHUR', 'z' => 'VELLORE ZONE'],
        'ARAKKONAM' => ['c' => 'Arakkonam', 'd' => 'RANIPET', 'z' => 'VELLORE ZONE'],
        'SHOLINGHUR' => ['c' => 'Sholinghur', 'd' => 'RANIPET', 'z' => 'VELLORE ZONE'],
        'RANIPET' => ['c' => 'Ranipet', 'd' => 'RANIPET', 'z' => 'VELLORE ZONE'],
        'ARCOT' => ['c' => 'Arcot', 'd' => 'RANIPET', 'z' => 'VELLORE ZONE'],
        'PALACODU' => ['c' => 'Palacodu', 'd' => 'DHARMAPURI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'PENNAGARAM' => ['c' => 'Pennagaram', 'd' => 'DHARMAPURI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'DHARMAPURI' => ['c' => 'Dharmapuri', 'd' => 'DHARMAPURI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'PAPPIREDDIPATTI' => ['c' => 'Pappireddipatti', 'd' => 'DHARMAPURI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'HARUR' => ['c' => 'Harur', 'd' => 'DHARMAPURI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'CHENGAM' => ['c' => 'Chengam', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'TIRUVANNAMALAI' => ['c' => 'Tiruvannamalai', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'KILPENNATHUR' => ['c' => 'Kilpennathur', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'KALASAPAKKAM' => ['c' => 'Kalasapakkam', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'POLUR' => ['c' => 'Polur', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'ARANI' => ['c' => 'Arani', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'CHEYYAR' => ['c' => 'Cheyyar', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'VANDAVASI' => ['c' => 'Vandavasi', 'd' => 'TIRUVANNAMALAI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'ULUNDURPETTAI' => ['c' => 'Ulundurpettai', 'd' => 'KALLAKURUCHI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'RISHIVANDIYAM' => ['c' => 'Rishivandiyam', 'd' => 'KALLAKURUCHI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'SANKARAPURAM' => ['c' => 'Sankarapuram', 'd' => 'KALLAKURUCHI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'KALLAKURICHI' => ['c' => 'Kallakurichi', 'd' => 'KALLAKURUCHI', 'z' => 'TIRUVANNAMALAI ZONE'],
        'GINGEE' => ['c' => 'Gingee', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'MAILAM' => ['c' => 'Mailam', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'TINDIVANAM' => ['c' => 'Tindivanam', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'VANUR' => ['c' => 'Vanur', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'VILUPPURAM' => ['c' => 'Viluppuram', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'VIKRAVANDI' => ['c' => 'Vikravandi', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'TIRUKKOYILUR' => ['c' => 'Tirukkoyilur', 'd' => 'VILUPURAM', 'z' => 'VILLUPURAM ZONE'],
        'TITTAKUDI' => ['c' => 'Tittakudi', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'VRIDDHACHALAM' => ['c' => 'Vriddhachalam', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'NEYVELI' => ['c' => 'Neyveli', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'PANRUTI' => ['c' => 'Panruti', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'CUDDALORE' => ['c' => 'Cuddalore', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'KURINJIPADI' => ['c' => 'Kurinjipadi', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'BHUVANAGIRI' => ['c' => 'Bhuvanagiri', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'CHIDAMBARAM' => ['c' => 'Chidambaram', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'KATTUMANNARKOIL' => ['c' => 'Kattumannarkoil', 'd' => 'CUDDALORE', 'z' => 'VILLUPURAM ZONE'],
        'GANGAVALLI' => ['c' => 'Gangavalli', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'ATTUR' => ['c' => 'Attur', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'YERCAUD' => ['c' => 'Yercaud', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'OMALUR' => ['c' => 'Omalur', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'METTUR' => ['c' => 'Mettur', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'EDAPPADI' => ['c' => 'Edappadi', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'SANKARI' => ['c' => 'Sankari', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'SALEM (WEST)' => ['c' => 'Salem (West)', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'SALEM (NORTH)' => ['c' => 'Salem (North)', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'SALEM (SOUTH)' => ['c' => 'Salem (South)', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'VEERAPANDI' => ['c' => 'Veerapandi', 'd' => 'SALEM', 'z' => 'SALEM ZONE'],
        'RASIPURAM' => ['c' => 'Rasipuram', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'SENTHAMANGALAM' => ['c' => 'Senthamangalam', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'NAMAKKAL' => ['c' => 'Namakkal', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'PARAMATHI-VELUR' => ['c' => 'Paramathi-Velur', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'TIRUCHENGODU' => ['c' => 'Tiruchengodu', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'KUMARAPALAYAM' => ['c' => 'Kumarapalayam', 'd' => 'NAMAKKAL', 'z' => 'SALEM ZONE'],
        'ERODE (EAST)' => ['c' => 'Erode (East)', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'ERODE (WEST)' => ['c' => 'Erode (West)', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'MODAKKURICHI' => ['c' => 'Modakkurichi', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'PERUNDURAI' => ['c' => 'Perundurai', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'BHAVANI' => ['c' => 'Bhavani', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'ANTHIYUR' => ['c' => 'Anthiyur', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'GOBICHETTIPALAYAM' => ['c' => 'Gobichettipalayam', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'BHAVANISAGAR' => ['c' => 'Bhavanisagar', 'd' => 'ERODE', 'z' => 'SALEM ZONE'],
        'UDHAGAMANDALAM' => ['c' => 'Udhagamandalam', 'd' => 'NILGIRIS', 'z' => 'COVAI ZONE'],
        'GUDALUR' => ['c' => 'Gudalur', 'd' => 'NILGIRIS', 'z' => 'COVAI ZONE'],
        'COONOOR' => ['c' => 'Coonoor', 'd' => 'NILGIRIS', 'z' => 'COVAI ZONE'],
        'METTUPPALAYAM' => ['c' => 'Mettuppalayam', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'SULUR' => ['c' => 'Sulur', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'KAVUNDAMPALAYAM' => ['c' => 'Kavundampalayam', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'COIMBATORE (NORTH)' => ['c' => 'Coimbatore (North)', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'THONDAMUTHUR' => ['c' => 'Thondamuthur', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'COIMBATORE (SOUTH)' => ['c' => 'Coimbatore (South)', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'SINGANALLUR' => ['c' => 'Singanallur', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'KINATHUKADAVU' => ['c' => 'Kinathukadavu', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'POLLACHI' => ['c' => 'Pollachi', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'VALPARAI' => ['c' => 'Valparai', 'd' => 'COIMBATORE', 'z' => 'COVAI ZONE'],
        'DHARAPURAM' => ['c' => 'Dharapuram', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'KANGAYAM' => ['c' => 'Kangayam', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'AVANASHI' => ['c' => 'Avanashi', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'TIRUPPUR (NORTH)' => ['c' => 'Tiruppur (North)', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'TIRUPPUR (SOUTH)' => ['c' => 'Tiruppur (South)', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'PALLADAM' => ['c' => 'Palladam', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'UDUMALAIPETTAI' => ['c' => 'Udumalaipettai', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'MADATHUKULAM' => ['c' => 'Madathukulam', 'd' => 'TIRUPPUR', 'z' => 'COVAI ZONE'],
        'ARAVAKURICHI' => ['c' => 'Aravakurichi', 'd' => 'KARUR', 'z' => 'TRICHY ZONE'],
        'KARUR' => ['c' => 'Karur', 'd' => 'KARUR', 'z' => 'TRICHY ZONE'],
        'KRISHNARAYAPURAM' => ['c' => 'Krishnarayapuram', 'd' => 'KARUR', 'z' => 'TRICHY ZONE'],
        'KULITHALAI' => ['c' => 'Kulithalai', 'd' => 'KARUR', 'z' => 'TRICHY ZONE'],
        'MANAPPARAI' => ['c' => 'Manapparai', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'SRIRANGAM' => ['c' => 'Srirangam', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'TIRUCHIRAPPALLI (WEST)' => ['c' => 'Tiruchirappalli  (West)', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'TIRUCHIRAPPALLI (EAST)' => ['c' => 'Tiruchirappalli  (East)', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'THIRUVERUMBUR' => ['c' => 'Thiruverumbur', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'LALGUDI' => ['c' => 'Lalgudi', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'MANACHANALLUR' => ['c' => 'Manachanallur', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'MUSIRI' => ['c' => 'Musiri', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'THURAIYUR' => ['c' => 'Thuraiyur', 'd' => 'TIRUCHIRAPALLI', 'z' => 'TRICHY ZONE'],
        'PERAMBALUR' => ['c' => 'Perambalur', 'd' => 'PERAMBALUR', 'z' => 'TRICHY ZONE'],
        'KUNNAM' => ['c' => 'Kunnam', 'd' => 'PERAMBALUR', 'z' => 'TRICHY ZONE'],
        'GANDARVAKKOTTAI' => ['c' => 'Gandarvakkottai', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'VIRALIMALAI' => ['c' => 'Viralimalai', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'PUDUKKOTTAI' => ['c' => 'Pudukkottai', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'THIRUMAYAM' => ['c' => 'Thirumayam', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'ALANGUDI' => ['c' => 'Alangudi', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'ARANTHANGI' => ['c' => 'Aranthangi', 'd' => 'PUDUKOTTAI', 'z' => 'TRICHY ZONE'],
        'ARIYALUR' => ['c' => 'Ariyalur', 'd' => 'ARIYALUR', 'z' => 'TRICHY ZONE'],
        'JAYANKONDAM' => ['c' => 'Jayankondam', 'd' => 'ARIYALUR', 'z' => 'TRICHY ZONE'],
        'PALANI' => ['c' => 'Palani', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'ODDANCHATRAM' => ['c' => 'Oddanchatram', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'ATHOOR' => ['c' => 'Athoor', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'NILAKKOTTAI' => ['c' => 'Nilakkottai', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'NATHAM' => ['c' => 'Natham', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'DINDIGUL' => ['c' => 'Dindigul', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'VEDASANDUR' => ['c' => 'Vedasandur', 'd' => 'DINDIGUL', 'z' => 'VIRUDHUNAGAR ZONE'],
        'ANDIPATTI' => ['c' => 'Andipatti', 'd' => 'THENI', 'z' => 'VIRUDHUNAGAR ZONE'],
        'PERIYAKULAM' => ['c' => 'Periyakulam', 'd' => 'THENI', 'z' => 'VIRUDHUNAGAR ZONE'],
        'BODINAYAKANUR' => ['c' => 'Bodinayakanur', 'd' => 'THENI', 'z' => 'VIRUDHUNAGAR ZONE'],
        'CUMBUM' => ['c' => 'Cumbum', 'd' => 'THENI', 'z' => 'VIRUDHUNAGAR ZONE'],
        'RAJAPALAYAM' => ['c' => 'Rajapalayam', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'SRIVILLIPUTHUR' => ['c' => 'Srivilliputhur', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'SATTUR' => ['c' => 'Sattur', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'SIVAKASI' => ['c' => 'Sivakasi', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'VIRUDHUNAGAR' => ['c' => 'Virudhunagar', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'ARUPPUKKOTTAI' => ['c' => 'Aruppukkottai', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'TIRUCHULI' => ['c' => 'Tiruchuli', 'd' => 'VIRUDHUNAGAR', 'z' => 'VIRUDHUNAGAR ZONE'],
        'NAGAPATTINAM' => ['c' => 'Nagapattinam', 'd' => 'NAGAPATTINAM', 'z' => 'THANJAI ZONE'],
        'KILVELUR' => ['c' => 'Kilvelur', 'd' => 'NAGAPATTINAM', 'z' => 'THANJAI ZONE'],
        'VEDARANYAM' => ['c' => 'Vedaranyam', 'd' => 'NAGAPATTINAM', 'z' => 'THANJAI ZONE'],
        'THIRUTHURAIPOONDI' => ['c' => 'Thiruthuraipoondi', 'd' => 'THIRUVARUR', 'z' => 'THANJAI ZONE'],
        'MANNARGUDI' => ['c' => 'Mannargudi', 'd' => 'THIRUVARUR', 'z' => 'THANJAI ZONE'],
        'THIRUVARUR' => ['c' => 'Thiruvarur', 'd' => 'THIRUVARUR', 'z' => 'THANJAI ZONE'],
        'NANNILAM' => ['c' => 'Nannilam', 'd' => 'THIRUVARUR', 'z' => 'THANJAI ZONE'],
        'THIRUVIDAIMARUDUR' => ['c' => 'Thiruvidaimarudur', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'KUMBAKONAM' => ['c' => 'Kumbakonam', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'PAPANASAM' => ['c' => 'Papanasam', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'THIRUVAIYARU' => ['c' => 'Thiruvaiyaru', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'THANJAVUR' => ['c' => 'Thanjavur', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'ORATHANADU' => ['c' => 'Orathanadu', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'PATTUKKOTTAI' => ['c' => 'Pattukkottai', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'PERAVURANI' => ['c' => 'Peravurani', 'd' => 'THANJAVUR', 'z' => 'THANJAI ZONE'],
        'SIRKAZHI' => ['c' => 'Sirkazhi', 'd' => 'MAYILADUTHURAI', 'z' => 'THANJAI ZONE'],
        'MAYILADUTHURAI' => ['c' => 'Mayiladuthurai', 'd' => 'MAYILADUTHURAI', 'z' => 'THANJAI ZONE'],
        'POOMPUHAR' => ['c' => 'Poompuhar', 'd' => 'MAYILADUTHURAI', 'z' => 'THANJAI ZONE'],
        'KARAIKUDI' => ['c' => 'Karaikudi', 'd' => 'SIVAGANGA', 'z' => 'MADURAI ZONE'],
        'TIRUPPATTUR' => ['c' => 'Tiruppattur', 'd' => 'SIVAGANGA', 'z' => 'MADURAI ZONE'],
        'SIVAGANGA' => ['c' => 'Sivaganga', 'd' => 'SIVAGANGA', 'z' => 'MADURAI ZONE'],
        'MANAMADURAI' => ['c' => 'Manamadurai', 'd' => 'SIVAGANGA', 'z' => 'MADURAI ZONE'],
        'MELUR' => ['c' => 'Melur', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'MADURAI EAST' => ['c' => 'Madurai East', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'SHOLAVANDAN' => ['c' => 'Sholavandan', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'MADURAI NORTH' => ['c' => 'Madurai North', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'MADURAI SOUTH' => ['c' => 'Madurai South', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'MADURAI CENTRAL' => ['c' => 'Madurai Central', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'MADURAI WEST' => ['c' => 'Madurai West', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'THIRUPARANKUNDRAM' => ['c' => 'Thiruparankundram', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'THIRUMANGALAM' => ['c' => 'Thirumangalam', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'USILAMPATTI' => ['c' => 'Usilampatti', 'd' => 'MADURAI', 'z' => 'MADURAI ZONE'],
        'PARAMAKUDI' => ['c' => 'Paramakudi', 'd' => 'RAMANATHAPURAM', 'z' => 'MADURAI ZONE'],
        'TIRUVADANAI' => ['c' => 'Tiruvadanai', 'd' => 'RAMANATHAPURAM', 'z' => 'MADURAI ZONE'],
        'RAMANATHAPURAM' => ['c' => 'Ramanathapuram', 'd' => 'RAMANATHAPURAM', 'z' => 'MADURAI ZONE'],
        'MUDHUKULATHUR' => ['c' => 'Mudhukulathur', 'd' => 'RAMANATHAPURAM', 'z' => 'MADURAI ZONE'],
        'VILATHIKULAM' => ['c' => 'Vilathikulam', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'THOOTHUKKUDI' => ['c' => 'Thoothukkudi', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'TIRUCHENDUR' => ['c' => 'Tiruchendur', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'SRIVAIKUNTAM' => ['c' => 'Srivaikuntam', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'OTTAPIDARAM' => ['c' => 'Ottapidaram', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'KOVILPATTI' => ['c' => 'Kovilpatti', 'd' => 'THOOTHUKUDI', 'z' => 'TIRUNELVELI ZONE'],
        'TIRUNELVELI' => ['c' => 'Tirunelveli', 'd' => 'TIRUNELVELI', 'z' => 'TIRUNELVELI ZONE'],
        'AMBASAMUDRAM' => ['c' => 'Ambasamudram', 'd' => 'TIRUNELVELI', 'z' => 'TIRUNELVELI ZONE'],
        'PALAYAMKOTTAI' => ['c' => 'Palayamkottai', 'd' => 'TIRUNELVELI', 'z' => 'TIRUNELVELI ZONE'],
        'NANGUNERI' => ['c' => 'Nanguneri', 'd' => 'TIRUNELVELI', 'z' => 'TIRUNELVELI ZONE'],
        'RADHAPURAM' => ['c' => 'Radhapuram', 'd' => 'TIRUNELVELI', 'z' => 'TIRUNELVELI ZONE'],
        'KANNIYAKUMARI' => ['c' => 'Kanniyakumari', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'NAGERCOIL' => ['c' => 'Nagercoil', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'COLACHAL' => ['c' => 'Colachal', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'PADMANABHAPURAM' => ['c' => 'Padmanabhapuram', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'VILAVANCODE' => ['c' => 'Vilavancode', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'KILLIYOOR' => ['c' => 'Killiyoor', 'd' => 'KANNIYAKUMARI', 'z' => 'TIRUNELVELI ZONE'],
        'SANKARANKOVIL' => ['c' => 'Sankarankovil', 'd' => 'TENKASI', 'z' => 'TIRUNELVELI ZONE'],
        'VASUDEVANALLUR' => ['c' => 'Vasudevanallur', 'd' => 'TENKASI', 'z' => 'TIRUNELVELI ZONE'],
        'KADAYANALLUR' => ['c' => 'Kadayanallur', 'd' => 'TENKASI', 'z' => 'TIRUNELVELI ZONE'],
        'TENKASI' => ['c' => 'Tenkasi', 'd' => 'TENKASI', 'z' => 'TIRUNELVELI ZONE'],
        'ALANGULAM' => ['c' => 'Alangulam', 'd' => 'TENKASI', 'z' => 'TIRUNELVELI ZONE'],
    ],
];
